version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=cookiebug
    ports:
      - "1107:3000"
    depends_on:
      - mongo
    restart: always
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 1
  mongo:
    image: mongo
    ports:
      - "27019:27017"
    restart: always
    mem_limit: 512M
    mem_reservation: 128M
    cpus: 1