version: "3.3"

services:
  server:
    build: .
    ports:
      - "1302:1337"
    environment:
      - FLAG="AlphaCTF{A_s7ar_paTHfiND1ng_m4s73r}"
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M