version: '3'

services:
  server:
    build: .
    ports:
      - 1337:1337
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
