version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=cookiebug
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
