version: '3.8'

services:
  web:
    build: .
    image: "911"
    environment:
      - FLAG="AlphaCTF{1M_rE4Dy_t0_b3_4_WEB_HacKEr_yay}"
    ports:
      - 1100:8000
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M