version: '2'

services:
  crver:
    image: crver_image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crver_container
    ports:
      - "41340:1337"
    restart: always
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 1
    
