version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 1108:3000
    restart: always
    mem_limit: 512M
    mem_reservation: 128M
    cpus: 1
