version: '2'
services:
  prison_realm:
    build: .
    image: prison_realm
    container_name: prison_realm_chall
    ports:
      - 1000:1337
    hostname: kingdom
    read_only: true
    volumes:
      - prison_realm_volume:/home/alpha/prison_realm/tmp/
    networks:
      - prison_realm_network
    restart: always
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 1
volumes:
  prison_realm_volume:
    name: prison_realm_volume
    driver: local

networks:
  prison_realm_network:
    name: prison_realm_network
    driver: bridge
