version: '3'

services:
  web:
    build: .
    image: "proxy"
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - ./challenge/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

