version: '3.8'

services:
  web:
    build: .
    image: "proxy"
    ports:
      - 1104:5000
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    depends_on:
      - nginx


  nginx:
    image: nginx:alpine
    volumes:
      - ./challenge/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M

