version: '2'

services:
  web:
    build: .
    image: "proxy"
    ports:
      - 1104:5000

    depends_on:
      - nginx
    restart: always
    mem_limit: 512M
    mem_reservation: 128M
    cpus: 1


  nginx:
    image: nginx:alpine
    volumes:
      - ./challenge/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    mem_limit: 512M
    mem_reservation: 128M
    cpus: 1

