version: '2'

services:
  web:
    build: .
    image: "proxy"
    ports:
      - 1104:5000

    depends_on:
      - nginx


  nginx:
    image: nginx:alpine
    volumes:
      - ./challenge/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always


