version: '3.8'

services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 1103:80
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    depends_on:
      - php-fpm
    links:
      - php-fpm
    volumes:
      - ./challenge/:/var/www/html/

    
  php-fpm:
    image: php:8-fpm
    expose:
      - 9000
    volumes:
      - ./challenge/:/var/www/html/
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
