version: "3.3"

services:
  server:
    build: .
    ports:
      - "1107:1337"
    image: wizzard
    environment:
      - FLAG=AlphaCTF{a_wizzARd_KN0wS_H1s_Bi7W1s3_0Per4tiONs}
    restart: always
    healthcheck:
      test: socat - TCP4:localhost:1337 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5