version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1101:1337
    environment:
      - FLAG=AlphaCTF{y0u_4r3_4_SQLI_M4S73R}

    restart: always
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 0.5