version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1101:1337
    environment:
      - FLAG=AlphaCTF{y0u_4r3_4_SQLI_M4S73R}
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
