version: '2'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ez-http
    environment:
      - FLAG=AlphaCTF{H7tP_G0E5_PRrRrrrrRrrRRr}
    ports:
      - "51337:8000"
    restart: always
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 1
