version: '2'

services:
  neo-db:
    image: neo4j:4.4-community
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/super_secret_you_cant_gusss_it
    volumes:
      - data:/data
      - logs:/logs
    restart: always
    mem_limit: 1024M
    mem_reservation: 128M
    cpus: 1

  python-app:
    build: .
    ports:
      - "1109:8000"
    environment:
      - NEO4J_URI=neo4j://neo-db:7687
      - USER_NAME=neo4j
      - PASSWORD=super_secret_you_cant_gusss_it
    depends_on:
      - neo-db
    restart: always
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 1

volumes:
  data:
  logs:
