version: "3.3"

services:
  server:
    build: .
    ports:
      - "1303:1337"
    environment:
      - FLAG="AlphaCTF{PIzz4_Fu3L_0Pt1m1ZaT1oN_1337}"
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M