version: "2"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1309:1114"
    restart: always
    mem_limit: 512M
    mem_reservation: 128M
    cpus: 1
