version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1102:1330
    depends_on:
      - database
    environment:
      - FLAG=AlphaCTF{7H3_PR0BL3M_W4S_N3V3R_1N_SQL_Y0U_JUST_h4v3_SK1LL_1SSU3S}
      - DB_URI=mongodb://database:27017/NO_SQLI
    restart: always
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 1

  database:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    restart: always
    mem_limit: 512M
    mem_reservation: 128M
    cpus: 0.75


volumes:
  mongodata: {}
