version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - "1308:2323"
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M