version: "3.3"

services:
  server:
    build: .
    environment:
      - TOKEN=MTIxMTk3NDkwMzI4MTIyMTY0Mw.Go4V80.lT3wPe_MH7Vk2FTydKjnT5aATJyWsvEmSFlsOk
      - GIFT="MTIxMzU4MzgxMTE4NzgzNDk3MA.GarEwu.iUGt_9acezO0JSejmIO5iIvcqPj_vuh2rtqMyg"
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M