FROM ubuntu:24.04 AS build

RUN apt-get -y update && apt-get install -y \
    autoconf \
    bison \
    flex \
    gcc \
    g++ \
    git \
    libprotobuf-dev \
    libnl-route-3-dev \
    libtool \
    make \
    pkg-config \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/google/nsjail.git --depth 1 && \
    cd /nsjail && make && mv /nsjail/nsjail /bin && rm -rf  -- /nsjail

FROM ubuntu:24.04 AS chall

RUN apt update && \
    apt install \
    socat \
    cron \
    libprotobuf-dev \
    libnl-route-3-dev \
    libtool \
    -y && \
    rm -r /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash ctf && echo "ctf:ctf" | chpasswd
WORKDIR /home/ctf

COPY ./challenge/ ./

COPY --from=build /bin/nsjail /bin/nsjail
RUN mv flag.txt /root/flag.txt && \
    mv D /root/D_bak && \
    mv check_deleted.sh /var/tmp/check_deleted.sh && \
    mv entrypoint.sh /.entrypoint.sh && \
    mv send_gift /root/send_gift_bak && \
    chmod 666 /root/D_bak &&\
    chown ctf:ctf /root/D_bak && \ 
    chmod 000 /root/flag.txt && chown root:root /root/flag.txt && \
    chmod a+x /var/tmp/check_deleted.sh && \
    chmod u+x /.entrypoint.sh

RUN cp -p /root/send_gift_bak /etc/cron.d/send_gift && cp /root/D_bak /home/ctf/D

EXPOSE 1337

ENTRYPOINT ["/.entrypoint.sh"]
