version: "3.3"

services:
  server:
    build: .
    ports:
      - "1301:1337"
    environment:
      - FLAG="AlphaCTF{1_h0p3_u_u5ed_numPy_1nSTEAd_0F_manUalLY_MAk1Ng_L157s}"
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
